### ISSUE TITLE
Spotless maven plugin

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/benchmark#5]
We should aim to use the same coding style that deephaven-core uses.

https://github.com/diffplug/spotless/tree/main/plugin-maven

Here's how deephaven-core invokes spotless:
* [io.deephaven.java-coding-conventions.gradle](https://github.com/deephaven/deephaven-core/blob/main/buildSrc/src/main/groovy/io.deephaven.java-coding-conventions.gradle)
* [eclipse-java-google-style.xml](https://github.com/deephaven/deephaven-core/blob/main/style/eclipse-java-google-style.xml)

Obviously, the invocations will be different because this is using maven; but we should be able to use the same style file.

**Comment by stanbrub** [comment]
I was playing around with spotless.  Doesn't look like it's platform independent.  I have the output "Cannot run program "\usr\bin\git" showing when I run it.  There's probably a config somewhere, or maybe the default is good enough.

**Comment by devinrsmith** [comment]
Huh - that's strange. I wonder what it's doing executing git? We could open an issue in the upstream repo.

**Comment by stanbrub** [comment]
So I finally got this working.  There were multiple issues with it:
* Error message above. Seems to be harmless
* eclipse-java-google-style.xml from deephaven-core is not up to date with Java 17
* There was no support for records or text blocks (other things were missing that I'm not using)

Things done to get this working:
* Added Spotless to Maven verify and referenced eclipse-java-google-style.xml file in project dir
* Using eclipse-java-google-style.xml as a base, made a new style formatter for Benchmark that works from Eclipse Source Format and Spotless
* Detection of line endings by spotless required changing autocrlf in git for windows.  (Added comment in project pom to that effect.)
* Lots of reformatting of classes (mostly whitespace) including getting rid of my beloved tabs
* Many tests going back and forth between source changes, IDE formatting, and spotless
* Text blocks are now set to "do not touch", given the variability of usage
