### ISSUE TITLE
Floating points used for operation benchmarks

### ISSUE THREAD

**Issue by stanbrub** [deephaven/benchmark#63]
All current benchmark operations are using integers for calculations.  Add some comparable benchmarks for agg operations that use floats instead of ints for the same benchmark operation.
- Do we need float generation other than 1.0, 2.0?
- Do all operations need this or just combo tests or a sampling of operations?

**Comment by lbooker42** [comment]
Series of 1.0, 2.0 are perfectly acceptable for `float` or `double` values. I think only certain tests will need this, i.e. when we expect there to be performance differences between primitive and floating inputs.
