### ISSUE TITLE
More combo tests for update_by cum vs rolling

### ISSUE THREAD

**Issue by stanbrub** [deephaven/benchmark#64]
Create more combo tests:
- cumulative combo: cum_max, cum_min, cum_sum, cum_prod, ema_tick_decay, ema_time_decay
- rolling combo: rolling_sum_tick, rolling_sum_time, rolling_avg_tick, rolling_avg_time
- mixed combo: all of the above

**Comment by lbooker42** [comment]
`ema_tick_decay`, `ema_time_decay` are cumulative operations despite the acceptance of `time`/`tick` parameters.
